title: Your awesome title
theme: minima
author: GitHub User
email: joshuasevy@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Tips and Tricks for Jr. Developers and great practice for myself with writing. 

# social links
twitter_username: JoshSevy # DO NOT include the @ character, or else the build will fail!
github_username:  JoshSevy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
